
@url=http://localhost:3000/api
@json=Content-Type: application/json
### 所有用户
GET {{url}}/users
### 注册
POST {{url}}/register
{{json}}

{
    "username":"user3",
    "password":"123456"
}
### 登录
POST {{url}}/login
{{json}}

{
    "username":"user3",
    "password":"123456"
}
### 个人信息
GET {{url}}/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZTNhNDYyMzRkNTM1MzAzOTk5OTM0ZSIsImlhdCI6MTY1OTA4ODg3MH0.MKh4aLFmyJSsOtucLF3xWScDE4PgbjCEiFXv3YdZ5xM